#index:
#    path: /
#    controller: App\Controller\DefaultController::index
medicos:
  path: /medicos
  controller: App\Controller\MedicoController::findAll
  methods:
    - GET

medico:
  path: /medicos/{id}
  controller: App\Controller\MedicoController::find
  methods:
    - GET

create_medico:
  path: /medicos
  controller: App\Controller\MedicoController::create
  methods:
    - POST

update_medico:
  path: /medicos/{id}
  controller: App\Controller\MedicoController::update
  methods:
    - PUT

remove_medico:
  path: /medicos/{id}
  controller: App\Controller\MedicoController::remove
  methods:
    - DELETE

especialidades:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::findAll
  methods:
    - GET

especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::find
  methods:
    - GET
    -
create_especialidade:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::create
  methods:
    - POST

update_especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::update
  methods:
    - PUT

remove_especialidade:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::remove
  methods:
    - DELETE
